### ISSUE TITLE
Godoc examples fail to work on Go 1.9.2

### ISSUE THREAD

**Issue by greatercommonsfernando** [olebedev/config#18]
The following YAML file:
```
development:
  database:
    host: localhost
  users:
    - name: calvin
      password: yukon
    - name: hobbes
      password: tuna
production:
  database:
    host: 192.168.1.1
```

With the following code:

```
    if cfg, err := config.ParseYaml("config.yml"); err != nil {
        panic(err)
    } else {
        if testValue, err := cfg.Get("development.database.host"); err != nil {
            panic(err)
        } else {
            fmt.Println("test:", testValue)
        }
    }
```

Fails with the following error: `Invalid type at "development": expected []interface{} or map[string]interface{}; got string`

Note that using cfg.Get or cfg.String results in the same error. YAML handling is non-functional with this library as of the latest revision. The code I have used is a slightly modified version of what is demonstrated in package godocs.
