### ISSUE TITLE
RenderYaml|Json adding spurious root

### ISSUE THREAD

**Issue by jenolan** [olebedev/config#19]
If you load a YAML|JSON with the ParsexxxxFile and then re-write a spurious entitiy of 'root' is added to the YAML|JSON.

This means that if you then subsequently reload the saved file it will have the spurious root, and most likely will then add another root which is pretty nasty.

**Comment by olebedev** [comment]
Hi @jenolan, thanks for using the library let me know the issue.

I think the problem you described located in a user space, not a library’s issue. So, if you change Root, be awere about that you can reach something weird. Also, immutability is not in go’s concept. 

I am closing this, feel free to open If you intend to further discussion. Thanks

**Comment by jenolan** [comment]
``` go
    cfg, err := config.ParseYamlFile( "hello.yaml" )
    if( err != nil ) {
        fmt.Printf( "Parse 'hello.yaml' Error %s\n", err )
    }
    str, err := config.RenderJson( cfg )
    if( err != nil ) {
        fmt.Printf( "Render 'hello.yaml' Error %s\n", err )
    }
    fmt.Printf( str )
    fmt.Printf( "\n" )
    str, err = config.RenderYaml( cfg )
    if( err != nil ) {
        fmt.Printf( "Render 'hello.yaml' Error %s\n", err )
    }
```
YAML file
``` yaml
Activity:
  KUID: "59904:101234:0"
  Name: "Test Activity"
Profile:
  KUID: "59904:201234:0"
  Name: "Test Profile"
Information:
  Author: "Jenolan"
  Title:  "JS01 HV Sampler"
  Description: "JS01 is a simple test Activity
    it should work pretty well, maybe, perhaps, but don't count on it\n
    Lines are split using the \n\n see?"
Build: 0
```
Output
```json
{"Root":{"Activity":{"KUID":"59904:101234:0","Name":"Test Activity"},"Build":0,"Information":{"Author":"Jenolan","Description":"JS01 is a simple test Activity it should work pretty well, maybe, perhaps, but don't count on it\n Lines are split using the \n\n see?","Title":"JS01 HV Sampler"},"Profile":{"KUID":"59904:201234:0","Name":"Test Profile"}}}
```
yaml
```yaml
root:
  Activity:
    KUID: 59904:101234:0
    Name: Test Activity
  Build: 0
  Information:
    Author: Jenolan
    Description: "JS01 is a simple test Activity it should work pretty well, maybe,
      perhaps, but don't count on it\n Lines are split using the \n\n see?"
    Title: JS01 HV Sampler
  Profile:
    KUID: 59904:201234:0
    Name: Test Profile
```
If either of the above are written to disk they are prefixed with the spurious 'ROOT' as shown so if I load the yaml file, modify it, then use the render to write it back out a 'root' is added every time this is surely not correct?
